import { useEffect } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowLeft, ShieldCheck } from 'lucide-react';
import Footer from '../components/Footer';
import NoiseOverlay from '../components/NoiseOverlay';
import { SITE_DATA } from '../data';

type LegalDoc = {
  eyebrow: string;
  title: string;
  summary: string;
  sections: Array<{
    title: string;
    body?: string;
    items?: string[];
  }>;
};

const lastUpdated = 'May 29, 2026';

const docs: Record<string, LegalDoc> = {
  '/privacy': {
    eyebrow: 'Privacy Policy',
    title: 'How Signal Lab handles personal data.',
    summary:
      'This policy explains what we collect when someone uses this site, requests a free audit, or contacts Signal Lab about a project.',
    sections: [
      {
        title: 'Data we collect',
        items: [
          'Contact details submitted through the audit form: name, email address, and optional business or website information.',
          'Messages, project context, files, links, and business information you choose to send us while discussing a project.',
          'Basic technical data generated by normal website use, such as device/browser information, page interactions, and security logs when hosting or analytics tools provide them.',
          'Public social profile interactions if you choose to contact Signal Lab through Instagram, TikTok, Facebook, email, or another platform.',
        ],
      },
      {
        title: 'How we use the data',
        items: [
          'To respond to audit requests, project inquiries, support questions, and follow-up messages.',
          'To understand the business leak, workflow, or system you asked us to review.',
          'To operate, protect, debug, and improve the website and lead capture flow.',
          'To prepare proposals, roadmaps, demos, websites, apps, automations, or AI systems you request.',
          'To comply with legal duties, prevent misuse, and document consent or communication history where needed.',
        ],
      },
      {
        title: 'Service providers',
        body:
          'Signal Lab may use infrastructure and workflow providers such as Vercel for hosting, Supabase for lead storage, email providers for communication, and analytics or security tools if they are enabled. We do not sell personal data.',
      },
      {
        title: 'Cookies and browser storage',
        body:
          'The current site does not need advertising cookies to submit an audit request. Hosting, security, analytics, or embedded platform tools may use essential cookies, local storage, logs, or similar browser technologies if those tools are enabled. Any future marketing cookie or tracking setup should be documented before launch.',
      },
      {
        title: 'Retention',
        body:
          'Lead and inquiry data is kept only as long as needed to respond, manage the business relationship, keep reasonable business records, protect against disputes, or meet legal obligations. If a project does not move forward, data can be deleted on request unless we have a legitimate reason or legal duty to keep it.',
      },
      {
        title: 'Your choices and rights',
        items: [
          'You may ask for access, correction, deletion, or restriction of personal data where applicable.',
          'You may ask us to stop contacting you for marketing or follow-up messages.',
          'If you are in a jurisdiction with additional privacy rights, we will handle requests according to the law that applies.',
          `To make a request, email ${SITE_DATA.personal.email}.`,
        ],
      },
      {
        title: 'Security',
        body:
          'We use practical safeguards such as HTTPS hosting, limited access, least-privilege workflows, and provider-level security controls. No online system can be guaranteed perfectly secure, so sensitive credentials, private keys, and production secrets should not be sent through general website forms.',
      },
    ],
  },
  '/terms': {
    eyebrow: 'Terms of Use',
    title: 'The rules for using this website and working with Signal Lab.',
    summary:
      'These terms cover the public Signal Lab website, free audit requests, demos, proposals, and early project discussions unless a signed agreement says otherwise.',
    sections: [
      {
        title: 'Website use',
        items: [
          'Use the site lawfully and do not attempt to disrupt, scrape, exploit, reverse engineer, or overload it.',
          'Do not submit illegal, confidential, infringing, harmful, or misleading material.',
          'The site is provided for information, portfolio, and inquiry purposes. Availability is not guaranteed.',
        ],
      },
      {
        title: 'Free audits and proposals',
        body:
          'A free audit or proposal is an initial business opinion based on the information available at the time. It is not a guarantee of revenue, leads, rankings, conversions, funding, or any specific result.',
      },
      {
        title: 'Project work',
        items: [
          'Project scope, price, ownership, timelines, maintenance, hosting, third-party tools, and payment terms should be confirmed in writing before build work starts.',
          'You are responsible for ensuring you have rights to the text, images, databases, customer lists, logos, and business materials you provide.',
          'AI-assisted research, design, copy, code, or automation may be used as part of the workflow, with human review before delivery where appropriate.',
        ],
      },
      {
        title: 'No professional advice',
        body:
          'Signal Lab builds business systems, websites, apps, automations, and AI workflows. Content on this site is not legal, financial, tax, medical, or regulated professional advice.',
      },
      {
        title: 'Third-party tools',
        body:
          'Projects may rely on services such as Vercel, Supabase, OpenAI, Google, Meta, Stripe, WhatsApp, or other providers. Their terms, limits, prices, outages, and policies are outside Signal Lab control unless a separate managed-service agreement states otherwise.',
      },
      {
        title: 'Limitation',
        body:
          'To the maximum extent allowed by law, Signal Lab is not liable for indirect, incidental, special, punitive, or consequential damages arising from website use, public portfolio content, or preliminary audit materials.',
      },
    ],
  },
  '/copyright': {
    eyebrow: 'Copyright & IP',
    title: 'Ownership, usage, and content rights.',
    summary:
      'This page clarifies how Signal Lab protects its own work and how client-provided content should be handled.',
    sections: [
      {
        title: 'Signal Lab materials',
        body:
          'The Signal Lab name, website design, copy, code, portfolio structure, visual assets, templates, demos, playbooks, and original content are protected by copyright and other intellectual property rights.',
      },
      {
        title: 'Client materials',
        items: [
          'You keep ownership of materials you provide, such as logos, product data, images, customer lists, text, credentials, or documents.',
          'By sending materials to Signal Lab, you confirm you have the right to use them and allow us to use them only for the requested project, audit, proposal, demo, or support work.',
          'If public case studies are created, sensitive client information should be approved, anonymized, or removed before publication.',
        ],
      },
      {
        title: 'Restrictions',
        items: [
          'Do not copy, resell, scrape, redistribute, or present Signal Lab work as your own without written permission.',
          'Do not remove copyright notices, brand marks, attribution, security controls, or license notices from delivered work unless the agreement permits it.',
          'Third-party logos, libraries, fonts, APIs, and assets remain owned by their respective rights holders.',
        ],
      },
      {
        title: 'Copyright notice',
        body:
          'Copyright 2026 Signal Lab. All rights reserved. For takedown, licensing, or permission requests, contact Signal Lab by email.',
      },
    ],
  },
  '/data-processing': {
    eyebrow: 'Data Processing',
    title: 'Client data, processors, and operational safeguards.',
    summary:
      'For client systems that store leads, customers, users, messages, analytics, or business records, the project needs a clear data-processing setup before launch.',
    sections: [
      {
        title: 'Roles',
        body:
          'In most client projects, the client is the controller or business owner of their customer data. Signal Lab may act as a processor/service provider when building, hosting, maintaining, or supporting the system according to client instructions.',
      },
      {
        title: 'Processing scope',
        items: [
          'Process client data only for agreed build, hosting, maintenance, support, security, debugging, analytics, or migration purposes.',
          'Use production access only when needed and keep access limited to the minimum people and tools required.',
          'Avoid putting unnecessary sensitive personal data into demos, tickets, prompts, spreadsheets, screenshots, or shared documents.',
        ],
      },
      {
        title: 'Subprocessors and AI tools',
        body:
          'Projects may use subprocessors such as hosting providers, databases, email tools, payment processors, analytics tools, and AI platforms. The final provider list should be documented in the project agreement or launch checklist.',
      },
      {
        title: 'Security baseline',
        items: [
          'HTTPS, role-based access, environment variables for secrets, backups, audit logs, and least-privilege permissions.',
          'No production secrets in public repositories, browser screenshots, public prompts, or static front-end files.',
          'Documented incident response, export, deletion, and handoff process before real users are onboarded.',
        ],
      },
      {
        title: 'End of project',
        body:
          'At project end, client data should be returned, deleted, exported, or transferred according to the written agreement, legal retention needs, backup limits, and the client instructions.',
      },
    ],
  },
};

function getDoc(pathname: string) {
  return docs[pathname] || docs['/privacy'];
}

export default function LegalPage() {
  const { pathname } = useLocation();
  const doc = getDoc(pathname);

  useEffect(() => {
    document.title = `${doc.eyebrow} | Signal Lab`;
  }, [doc.eyebrow]);

  return (
    <div className="relative min-h-screen bg-bg text-white">
      <NoiseOverlay />

      <main className="relative z-10 px-6 py-10 md:px-12">
        <div className="mx-auto max-w-5xl">
          <Link
            to="/"
            className="mb-10 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm font-bold text-text-muted transition-colors hover:border-signal/40 hover:text-white"
          >
            <ArrowLeft size={16} />
            Back to Signal Lab
          </Link>

          <section className="mb-10 overflow-hidden rounded-[2rem] border border-white/10 bg-white/[0.03] p-8 md:p-12 shadow-[0_30px_90px_rgba(0,0,0,0.35)]">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-signal/25 bg-signal/10 px-3 py-1.5">
              <ShieldCheck size={14} className="text-signal" />
              <span className="text-xs font-black uppercase tracking-[2px] text-signal">{doc.eyebrow}</span>
            </div>
            <p className="mb-3 text-sm font-semibold text-text-muted">Last updated: {lastUpdated}</p>
            <h1 className="max-w-4xl font-heading text-4xl font-black leading-tight tracking-tight md:text-6xl">
              {doc.title}
            </h1>
            <p className="mt-5 max-w-3xl text-base leading-8 text-text-muted md:text-lg">{doc.summary}</p>
          </section>

          <section className="grid gap-4">
            {doc.sections.map((section, index) => (
              <article key={section.title} className="rounded-2xl border border-white/10 bg-white/[0.035] p-6 md:p-8">
                <p className="mb-3 text-xs font-black uppercase tracking-[2px] text-signal">
                  {String(index + 1).padStart(2, '0')}
                </p>
                <h2 className="mb-3 text-2xl font-black tracking-tight text-white">{section.title}</h2>
                {section.body && <p className="leading-8 text-text-muted">{section.body}</p>}
                {section.items && (
                  <ul className="mt-3 grid gap-3 text-text-muted">
                    {section.items.map((item) => (
                      <li key={item} className="flex gap-3 leading-7">
                        <span className="mt-2 size-1.5 shrink-0 rounded-full bg-signal" />
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                )}
              </article>
            ))}
          </section>

          <div className="mt-8 rounded-2xl border border-amber-300/20 bg-amber-300/5 p-5 text-sm leading-7 text-text-muted">
            These pages are practical operating templates, not a substitute for legal advice. Review with a qualified lawyer before relying on them for a regulated launch, a paid SaaS product, or sensitive customer data.
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
