import {
  Globe, Smartphone, Bot, Mail,
  TrendingUp, Users, Clock, DollarSign,
  CheckCircle2, BarChart3, ShoppingCart,
  Package, CreditCard, Search, Workflow,
  ShieldCheck, FileText, Megaphone, Building2,
} from 'lucide-react';

export const SITE_DATA = {
  personal: {
    name: 'Yehonatan',
    brand: 'Signal Lab',
    email: 'jonathan@signal-lab-ops.com',
    emailSubject: 'I want a Free AI Audit - Signal Lab',
    instagram: 'https://www.instagram.com/signal.lab_/',
    instagramHandle: '@signal.lab_',
    tiktok: 'https://www.tiktok.com/@signal.lab',
    tiktokHandle: '@signal.lab',
    facebook: 'https://www.facebook.com/profile.php?id=100086763585884',
  },

  nav: {
    links: [
      { name: 'Home',     href: '#hero' },
      { name: 'Work',     href: '#showcase' },
      { name: 'Services', href: '#services' },
      { name: 'Results',  href: '#testimonials' },
      { name: 'Process',  href: '#process' },
    ],
    cta: 'Book a Call',
  },

  hero: {
    badge: 'AI Systems | Websites | Apps | Automation',
    eyebrow: 'Signal Lab',
    headline1: 'We turn AI',
    headline2: 'into revenue.',
    sub: "We build practical business systems: websites, apps, AI agents, automations, dashboards, internal tools, and lead systems that reduce manual work and turn demand into pipeline.",
    stats: [
      { num: 2000,  suffix: '+', label: 'Lead records mapped' },
      { num: 5000,  suffix: '+', label: 'SKUs structured' },
      { num: 1000,  suffix: '+', label: 'Audience built' },
    ],
  },

  ticker: [
    'React', 'Vite', 'TypeScript', 'Tailwind CSS', 'Framer Motion',
    'Expo', 'Supabase', 'PostgreSQL', 'Stripe', 'OpenAI',
    'Claude AI', 'Gemini', 'n8n', 'Make', 'WhatsApp API',
    'Meta Ads', 'Vercel', 'Firebase', 'Node.js', 'Next.js',
    'Shopify', 'WooCommerce', 'Zapier', 'Cal.com', 'Resend',
  ],

  painPoint: {
    headline: "You're leaving money on the table.",
    sub: 'Every day without the right systems is revenue your competitors are capturing instead.',
    pains: [
      { icon: Clock,      text: 'Hours wasted on manual tasks that AI could handle in seconds' },
      { icon: Users,      text: 'Leads going cold because there is no automated follow-up system' },
      { icon: TrendingUp, text: 'Website that looks like a business card, not a sales machine' },
      { icon: DollarSign, text: 'Missing payments because there is no 24/7 checkout flow' },
    ],
  },

  showcase: [
    {
      id: 'tomer-site',
      title: 'Tomer Friedman',
      type: 'Sales Website',
      desc: 'Sales website, quiz funnel, WhatsApp routing, and lead recovery infrastructure for 2,000+ dormant records.',
      stack: ['React', 'Vite', 'Tailwind', 'Framer Motion'],
      url: 'https://tf-nutritionist.com',
      metric: '12',
      metricLabel: 'sections wired to action',
      accentHex: '#ff6b35',
      theme: 'energy' as const,
    },
    {
      id: 'tomer-app',
      title: 'TF Tracker',
      type: 'iOS & Android App',
      desc: 'AI nutrition tracker concept and build path: photo-based food recognition, client logging, and coach-ready data flow.',
      stack: ['Expo', 'Supabase', 'Gemini AI', 'TypeScript'],
      url: null,
      metric: 'AI',
      metricLabel: 'photo recognition flow',
      accentHex: '#10b981',
      theme: 'health' as const,
    },
    {
      id: 'ron-ecom',
      title: "Ron's Store",
      type: 'E-Commerce Platform',
      desc: '5,000+ SKU catalog system with filtering, search, checkout flow, and admin workflows that cut repeated catalog work.',
      stack: ['React', 'Node.js', 'Stripe', 'PostgreSQL'],
      url: null,
      metric: '5,000+',
      metricLabel: 'live products',
      accentHex: '#00b4ff',
      theme: 'ecom' as const,
    },
  ],

  capabilities: {
    label: 'What we build',
    headline: 'Every weapon in the arsenal.',
    sub: "We don't specialize in one thing. We build the whole system.",
    items: [
      'AI Agents & Custom Bots', 'Sales Funnels & Websites',
      'Mobile Apps (iOS + Android)', 'Email Automation Systems',
      'Lead Generation Machines', 'CRM Integration & Setup',
      'Instagram & Facebook Ads', 'WhatsApp Automation',
      'Quiz & Survey Funnels', 'AI Content Systems',
      'Payment & Subscription Systems', 'Data Dashboards & Analytics',
      'n8n / Make / Zapier Workflows', 'Supabase & Firebase Backend',
      'Internal Tools & Staff Portals', 'Business Strategy & Roadmaps',
    ],
  },

  services: [
    {
      icon: Bot,
      color: 'signal' as const,
      title: 'AI Agents & Automation',
      desc: 'Custom AI agents for lead follow-up, intake, customer questions, reporting, and repeated operations that should not depend on copy-paste work.',
      tags: ['n8n', 'Make', 'OpenAI', 'Claude'],
    },
    {
      icon: Globe,
      color: 'violet' as const,
      title: 'Sales Websites & Funnels',
      desc: 'Fast websites and funnels that explain the offer clearly, capture demand, route leads, and give the business a system instead of a brochure.',
      tags: ['React', 'Vite', 'Tailwind', 'Framer'],
    },
    {
      icon: Smartphone,
      color: 'pink' as const,
      title: 'Mobile Applications',
      desc: 'iOS and Android apps with AI, subscriptions, payments, reminders, cloud sync, dashboards, and the workflows around the app.',
      tags: ['Expo', 'Supabase', 'TypeScript'],
    },
    {
      icon: ShoppingCart,
      color: 'green' as const,
      title: 'E-Commerce Platforms',
      desc: 'Custom storefronts handling thousands of SKUs. Advanced filtering, real-time search, Stripe checkout, admin dashboard.',
      tags: ['React', 'Stripe', 'PostgreSQL', 'Node.js'],
    },
    {
      icon: Mail,
      color: 'signal' as const,
      title: 'Email & Lead Systems',
      desc: 'Reactivate dormant lists, segment leads, build follow-up paths, and turn old demand into a cleaner call pipeline.',
      tags: ['Sequences', 'Segmentation', 'CRM'],
    },
    {
      icon: BarChart3,
      color: 'violet' as const,
      title: 'Strategy & Growth',
      desc: 'Offer strategy, growth roadmaps, dashboards, reporting, and practical prioritization: what to build first because it moves the business fastest.',
      tags: ['Meta Ads', 'Analytics', 'SEO'],
    },
  ],

  caseStudies: {
    tomer: {
      label: 'Case Study — Nutrition & Health',
      client: 'Tomer Friedman',
      clientTitle: 'Nutritionist & Fitness Coach · 22 years experience',
      summary: "Tomer had a site that did not explain the offer clearly, 2,000+ dormant lead records, and manual follow-up that was too easy to lose. We rebuilt the system around lead capture, WhatsApp routing, reactivation, and a cleaner sales path.",
      deliverables: [
        'Full React sales website with 12 sections, VSL, courses, quiz funnel, and 5 WhatsApp lead forms',
        'Mobile tracker app direction with AI food recognition, client logging, and coach-ready data',
        'Interactive lead quiz that filters clients by program and connects to WhatsApp',
        '5-7 touch reactivation sequence for 2,000+ dormant lead records with hot/warm/cold segmentation',
        'Sales battlecard + strategy for closing calls',
      ],
      metrics: [
        { num: '2,000+', label: 'Lead records',       sub: 'Mapped for reactivation' },
        { num: '10-16%', label: 'Recovery target',    sub: 'From dormant opportunity pools' },
        { num: '12',     label: 'Website sections',   sub: 'Hero / VSL / Courses / FAQ' },
        { num: '5',      label: 'Lead capture forms', sub: 'All wired to WhatsApp' },
      ],
      built: [
        { icon: Globe,        color: 'signal' as const, title: 'React Sales Website', desc: 'Hero, VSL, courses, quiz, app showcase, FAQ, and clear CTA routing built with React/Vite/Tailwind.' },
        { icon: Smartphone,   color: 'violet' as const, title: 'AI Tracker App',      desc: 'Calorie and macro tracking direction with AI food recognition, client history, and coach-facing data.' },
        { icon: CheckCircle2, color: 'green'  as const, title: 'Lead Quiz Funnel',    desc: 'Interactive quiz that filters clients by program and fires a WhatsApp message automatically.' },
        { icon: Mail,         color: 'pink'   as const, title: 'Lead Reactivation',   desc: 'Follow-up sequence and segmentation plan to turn old lead records into booked conversations.' },
      ],
      before: [
        'WordPress site that never converted',
        '2,000 leads sitting untouched in a spreadsheet',
        'No social proof or testimonials',
        'No app for clients',
        'Everything done manually',
        '3-10 leads per month',
      ],
      after: [
        'Fast React site converting 24/7',
        'Reactivation system for 2,000+ records',
        'Social proof + measurable results',
        'AI-powered client tracking app',
        '5 forms auto-routing to WhatsApp',
        'Target: 80-100 qualified leads/month',
      ],
    },

    ron: {
      label: 'Case Study — E-Commerce',
      client: "Ron's Store",
      clientTitle: 'E-Commerce · 5,000+ Products',
      summary: "Ron needed a custom e-commerce platform that could handle a large catalog without turning every update into manual admin work. We built the structure for search, filtering, checkout, and back-office control.",
      deliverables: [
        'Custom React storefront with real-time search and advanced multi-filter system',
        'Full product catalog management for 5,000+ SKUs, variants, and inventory tracking',
        'Stripe Checkout + subscription support with webhook-powered order automation',
        'Admin dashboard: orders, inventory, analytics, and customer management',
        'Performance-optimized catalog structure built for thousands of products',
      ],
      metrics: [
        { num: '5,000+', label: 'Live products',    sub: 'Full catalog management' },
        { num: '<2s',    label: 'Page load time',   sub: 'Even with 5K SKUs' },
        { num: 'Hours',  label: 'Saved weekly',     sub: 'Bulk catalog/admin workflows' },
        { num: '24/7',   label: 'Auto fulfillment', sub: 'Webhook-powered orders' },
      ],
      built: [
        { icon: ShoppingCart, color: 'signal' as const, title: 'Custom Storefront',  desc: 'React storefront with real-time search, advanced filtering by category, price, and attributes.' },
        { icon: Package,      color: 'violet' as const, title: 'Catalog Engine',      desc: '5,000+ SKUs with variants, inventory, bulk import/export, and category management.' },
        { icon: CreditCard,   color: 'green'  as const, title: 'Stripe Checkout',    desc: 'Full payment flow with webhook automation: order confirmed, inventory updated, customer notified.' },
        { icon: Search,       color: 'pink'   as const, title: 'Admin Dashboard',    desc: 'Full back-office: orders, customers, analytics, and inventory management in one place.' },
      ],
      before: [
        'Shopify limitations blocking growth',
        'Slow load times with large catalog',
        'No custom filtering capabilities',
        'Manual order management',
        'No real analytics or insights',
        'Paying high monthly SaaS fees',
      ],
      after: [
        'Custom storefront with zero limitations',
        'Sub-2s load even with 5,000+ products',
        'Advanced multi-attribute filtering',
        'Fully automated order fulfillment',
        'Real-time analytics dashboard',
        'One-time build cost - own your platform',
      ],
    },
  },

  proofLedger: {
    label: 'Proof Ledger',
    headline: 'Concrete systems, not AI theater.',
    sub: 'The common pattern: find the bottleneck, build the smallest useful system, and connect it to money, time saved, or operational clarity.',
    cards: [
      {
        icon: Mail,
        color: 'signal' as const,
        title: 'Dormant Lead Recovery',
        stat: '2,000+',
        statLabel: 'lead records mapped',
        body: 'Built segmentation, follow-up logic, and WhatsApp routing for a business with dormant demand sitting unused.',
        outcome: 'Goal: recover 10-16% of realistic opportunity pools instead of letting old leads disappear.',
      },
      {
        icon: Package,
        color: 'violet' as const,
        title: 'Large Catalog Systems',
        stat: '5,000+',
        statLabel: 'SKUs structured',
        body: 'Created a catalog/admin structure for search, filtering, inventory, checkout, and repeatable product handling.',
        outcome: 'Cuts repeated admin work and gives the owner a platform they can operate without SaaS limitations.',
      },
      {
        icon: Globe,
        color: 'green' as const,
        title: 'Hebrew RTL Business Site',
        stat: 'RTL',
        statLabel: 'site + contact flow',
        body: 'Built Hebrew-first site structure for a real local business, including service clarity, catalog/contact paths, and mobile-first layout.',
        outcome: 'Makes the business easier to understand, trust, and contact from the first visit.',
      },
      {
        icon: FileText,
        color: 'pink' as const,
        title: 'Accounting Office Systems',
        stat: 'Ops',
        statLabel: 'office workflow layer',
        body: 'Mapped practical systems for accountant-office workflows: intake, recurring tasks, document tracking, approvals, and client handoff.',
        outcome: 'Targets fewer missed tasks, cleaner follow-up, and less manual chasing inside service offices.',
      },
      {
        icon: Megaphone,
        color: 'signal' as const,
        title: 'Personal Brand Engine',
        stat: '1K+',
        statLabel: 'followers built',
        body: 'Built content systems around positioning, hooks, packaging, research, production rhythm, and feedback loops from real views and likes.',
        outcome: 'Turns posting into a measurable audience-building system instead of random content.',
      },
      {
        icon: Workflow,
        color: 'violet' as const,
        title: 'Agency AI Agent Builds',
        stat: 'AI',
        statLabel: 'agent workflows',
        body: 'Scoped and built AI assistant workflows for business owners inside a larger AI-focused agency environment.',
        outcome: 'Moves teams away from repeated manual work toward documented, testable AI-assisted workflows.',
      },
      {
        icon: ShieldCheck,
        color: 'green' as const,
        title: 'Defense Organization AI Systems',
        stat: 'Live',
        statLabel: 'sensitive environment',
        body: 'Currently implementing modern AI systems inside a sensitive defense organization. Details stay confidential by design.',
        outcome: 'Focus: reliable workflows, operational clarity, and practical AI adoption where mistakes are expensive.',
      },
      {
        icon: Building2,
        color: 'pink' as const,
        title: 'Business App And Tooling',
        stat: 'Full',
        statLabel: 'web/app/system stack',
        body: 'Signal Lab is not limited to one tool. We build websites, apps, automations, bots, dashboards, internal tools, and the glue between them.',
        outcome: 'The recommendation changes by business: whatever gets the owner away from pain and closer to the desired outcome fastest.',
      },
    ],
  },

  testimonials: [
    {
      name: 'Tomer Friedman',
      role: 'Nutritionist & Coach · tf-nutritionist.com',
      initials: 'TF',
      color: 'signal' as const,
      text: 'Yehonatan built my website, app, and entire marketing system from scratch. Unlike other agencies, he actually understands business. He is not just a contractor — he is a partner who delivers real results. He built in weeks what would have taken agencies months.',
    },
    {
      name: 'Ron',
      role: 'E-Commerce Founder',
      initials: 'R',
      color: 'violet' as const,
      text: 'Yehonatan is the kind of person you meet once in your career. Deep technical knowledge combined with real business thinking. He took our massive product catalog and built a platform that actually performs. The ROI was clear from day one.',
    },
  ],

  process: [
    { num: '01', title: 'Discovery Call', desc: "Free call. We understand your business, what exists, what is missing, and what will bring results fastest." },
    { num: '02', title: 'The Plan',       desc: 'We define exactly what to build, in what order, and what gets you ROI first. No vague proposals.' },
    { num: '03', title: 'We Build',       desc: 'Code, systems, automations. Fully transparent — you see progress at every step. We move fast.' },
    { num: '04', title: 'Results',        desc: "Deploy, measure, optimize. We do not disappear after launch. We track the numbers with you." },
  ],

  cta: {
    headline: 'Ready to build a system that gets you clients?',
    sub: 'First conversation is free. No commitment. No long contracts.',
    primary: 'Get My Free AI Audit',
    secondary: 'Follow @signal.lab_',
  },

  leadMagnet: {
    // Popup + inline CTA
    badge: 'FREE · Limited Spots',
    headline: 'Get Your Free AI Growth Audit',
    subheadline: "Here's exactly what you get:",
    bullets: [
      'A breakdown of which AI systems would 10x your revenue',
      'The #1 bottleneck killing your growth right now',
      'A prioritized roadmap — what to build first and why',
      'Honest assessment: what we would build if this were our business',
    ],
    why: "Most agencies pitch you a package before they understand your business. We do the homework first — so you get a real plan, not a sales deck.",
    ctaLabel: 'Send Me the Free Audit',
    namePlaceholder: 'Your name',
    emailPlaceholder: 'your@email.com',
    businessPlaceholder: 'Your website or business (optional)',
    disclaimer: 'Delivered to your inbox within 48h. Zero spam. Zero pitch.',
    successTitle: 'You are in.',
    successSub: 'Check your inbox in the next 48 hours. We will send you a personalized breakdown — built specifically for your business.',
    // Popup triggers
    scrollTrigger: 55,   // % scroll depth
    exitIntent: true,
    delayTrigger: 45,    // seconds on page
  },
};
