import {
  Globe, Smartphone, Bot, Mail,
  TrendingUp, Users, Clock, DollarSign,
  CheckCircle2, BarChart3, ShoppingCart,
  Package, CreditCard, Search, Workflow,
  ShieldCheck, FileText, Megaphone, Building2,
} from 'lucide-react';

export const SITE_DATA = {
  personal: {
    name: 'Yehonatan',
    brand: 'Signal Lab',
    site: 'https://signal-lab-ops.com/',
    email: 'jonathan@signal-lab-ops.com',
    emailSubject: 'I want a Free AI Audit - Signal Lab',
    instagram: 'https://www.instagram.com/signal.lab_/',
    instagramHandle: '@signal.lab_',
    tiktok: 'https://www.tiktok.com/@signal.lab',
    tiktokHandle: '@signal.lab',
    facebook: 'https://www.facebook.com/profile.php?id=100086763585884',
  },

  nav: {
    links: [
      { name: 'Home',     href: '#hero' },
      { name: 'Work',     href: '#showcase' },
      { name: 'Services', href: '#services' },
      { name: 'Results',  href: '#proof-ledger' },
      { name: 'Process',  href: '#process' },
    ],
    cta: 'Free AI Audit',
  },

  hero: {
    badge: 'AI Systems | Websites | Apps | Automation',
    eyebrow: 'Signal Lab',
    headline1: 'We turn AI',
    headline2: 'into revenue.',
    sub: "We inspect where leads, hours, or money are leaking, then build the right system: website, app, AI agent, automation, dashboard, internal tool, or follow-up engine.",
    stats: [
      { num: 16,    suffix: '%', label: 'Dormant-lead recovery target' },
      { num: 5000,  suffix: '+', label: 'SKUs structured' },
      { num: 1000,  suffix: '+', label: 'Audience built' },
    ],
  },

  ticker: [
    'React', 'Vite', 'TypeScript', 'Tailwind CSS', 'Framer Motion',
    'Expo', 'Supabase', 'PostgreSQL', 'Stripe', 'OpenAI',
    'Claude AI', 'Gemini', 'n8n', 'Make', 'WhatsApp API',
    'Meta Ads', 'Vercel', 'Firebase', 'Node.js', 'Next.js',
    'Shopify', 'WooCommerce', 'Zapier', 'Cal.com', 'Resend',
  ],

  painPoint: {
    headline: "You're leaving money on the table.",
    sub: 'Most businesses do not need another tool. They need the first leak found, priced, and fixed.',
    pains: [
      { icon: Clock,      text: '6-11 hours a week lost to admin, copy-paste, manual follow-up, and repeated updates' },
      { icon: Users,      text: '8-13 warm leads a month going cold because nobody catches them fast enough' },
      { icon: TrendingUp, text: 'A website that explains the business, but does not create qualified next steps' },
      { icon: DollarSign, text: 'Revenue stuck in old lead lists, unclear checkout flows, missed reminders, or weak intake' },
    ],
  },

  showcase: [
    {
      id: 'tomer-site',
      title: 'Tomer Friedman',
      type: 'Sales System',
      desc: 'Sales website, quiz funnel, WhatsApp routing, app direction, and reactivation logic for 2,000+ dormant lead records.',
      stack: ['React', 'Vite', 'Tailwind', 'Framer Motion'],
      url: 'https://tf-nutritionist.com',
      metric: '16%',
      metricLabel: 'reactivation target',
      accentHex: '#ff6b35',
      theme: 'energy' as const,
    },
    {
      id: 'tomer-app',
      title: 'TF Tracker',
      type: 'iOS & Android App',
      desc: 'AI nutrition tracker concept and build path: photo-based food recognition, client logging, and coach-ready data flow.',
      stack: ['Expo', 'Supabase', 'Gemini AI', 'TypeScript'],
      url: null,
      metric: 'AI',
      metricLabel: 'photo recognition flow',
      accentHex: '#10b981',
      theme: 'health' as const,
    },
    {
      id: 'hahai-vehatzomeach',
      title: 'Hahai VeHatzomeach',
      type: 'Hebrew RTL Website',
      desc: 'Hebrew-first business site with mobile-first structure, service clarity, catalog/contact paths, and practical local-business conversion flow.',
      stack: ['React', 'RTL UX', 'Lead Flow', 'Mobile'],
      url: null,
      metric: 'RTL',
      metricLabel: 'local-business flow',
      accentHex: '#22c55e',
      theme: 'ecom' as const,
    },
    {
      id: 'shova-accounting',
      title: 'Shova Ben Haim Systems',
      type: 'Accounting Office Tools',
      desc: 'Workflow and product systems for accounting firms: intake, document tracking, recurring tasks, client handoff, and operational dashboards.',
      stack: ['Workflow Design', 'CRM', 'Dashboards', 'AI Agents'],
      url: null,
      metric: '4-9h',
      metricLabel: 'weekly admin target',
      accentHex: '#f97316',
      theme: 'energy' as const,
    },
    {
      id: 'agency-ai-agents',
      title: 'Agency AI Agent Builds',
      type: 'AI Agent Systems',
      desc: 'Built and specified AI assistant workflows inside a larger AI-focused agency environment for business-owner operations and repetitive questions.',
      stack: ['OpenAI', 'n8n', 'Make', 'Workflow QA'],
      url: null,
      metric: 'AI',
      metricLabel: 'agent workflow layer',
      accentHex: '#8b5cf6',
      theme: 'health' as const,
    },
    {
      id: 'brand-engine',
      title: 'Personal Brand Engine',
      type: 'Audience System',
      desc: 'Built a content and positioning engine that passed 1K+ followers with hooks, packaging, production rhythm, and feedback from real views and likes.',
      stack: ['Content Ops', 'Positioning', 'Analytics', 'AI Research'],
      url: 'https://www.instagram.com/signal.lab_/',
      metric: '1K+',
      metricLabel: 'followers built',
      accentHex: '#00b4ff',
      theme: 'ecom' as const,
    },
  ],

  capabilities: {
    label: 'What we build',
    headline: 'The build depends on the leak.',
    sub: "We are not limited to one offer. The recommendation changes by what gets you away from pain and closer to revenue fastest.",
    items: [
      'AI Agents & Custom Bots', 'Sales Funnels & Websites',
      'Mobile Apps (iOS + Android)', 'Email Automation Systems',
      'Lead Generation Machines', 'CRM Integration & Setup',
      'Instagram & Facebook Ads', 'WhatsApp Automation',
      'Quiz & Survey Funnels', 'AI Content Systems',
      'Payment & Subscription Systems', 'Data Dashboards & Analytics',
      'n8n / Make / Zapier Workflows', 'Supabase & Firebase Backend',
      'Internal Tools & Staff Portals', 'Business Strategy & Roadmaps',
    ],
  },

  services: [
    {
      icon: Bot,
      color: 'signal' as const,
      title: 'AI Agents & Automation',
      desc: 'Custom AI agents for lead follow-up, intake, customer questions, reporting, and repeated operations that should not depend on copy-paste work.',
      tags: ['n8n', 'Make', 'OpenAI', 'Claude'],
    },
    {
      icon: Globe,
      color: 'violet' as const,
      title: 'Sales Websites & Funnels',
      desc: 'Websites and funnels that explain the offer, make the next step obvious, and route qualified demand instead of acting like a static brochure.',
      tags: ['React', 'Vite', 'Tailwind', 'Framer'],
    },
    {
      icon: Smartphone,
      color: 'pink' as const,
      title: 'Mobile Applications',
      desc: 'iOS and Android apps with AI, subscriptions, payments, reminders, cloud sync, dashboards, and the workflows around the app.',
      tags: ['Expo', 'Supabase', 'TypeScript'],
    },
    {
      icon: ShoppingCart,
      color: 'green' as const,
      title: 'E-Commerce Platforms',
      desc: 'Custom storefronts handling thousands of SKUs. Advanced filtering, real-time search, Stripe checkout, admin dashboard.',
      tags: ['React', 'Stripe', 'PostgreSQL', 'Node.js'],
    },
    {
      icon: Mail,
      color: 'signal' as const,
      title: 'Email & Lead Systems',
      desc: 'Reactivate dormant lists, segment leads, build follow-up paths, and turn old demand into a cleaner audit, call, or checkout pipeline.',
      tags: ['Sequences', 'Segmentation', 'CRM'],
    },
    {
      icon: BarChart3,
      color: 'violet' as const,
      title: 'Strategy & Growth',
      desc: 'Offer strategy, growth roadmaps, dashboards, reporting, and practical prioritization: what to build first because it moves the business fastest.',
      tags: ['Meta Ads', 'Analytics', 'SEO'],
    },
  ],

  caseStudies: {
    tomer: {
      label: 'Case Study - Nutrition & Health',
      client: 'Tomer Friedman',
      clientTitle: 'Nutritionist & Fitness Coach - 22 years experience',
      summary: "Tomer had a site that did not explain the offer clearly, 2,000+ dormant lead records, and manual follow-up that was too easy to lose. We rebuilt the system around lead capture, WhatsApp routing, app direction, reactivation, and a cleaner sales path.",
      deliverables: [
        'Full React sales website with 12 sections, VSL, courses, quiz funnel, and 5 WhatsApp lead forms',
        'Mobile tracker app direction with AI food recognition, client logging, and coach-ready data',
        'Interactive lead quiz that filters clients by program and connects to WhatsApp',
        '5-7 touch reactivation sequence for 2,000+ dormant lead records with hot/warm/cold segmentation',
        'Sales battlecard + strategy for closing calls',
      ],
      metrics: [
        { num: '2,000+', label: 'Lead records',       sub: 'Mapped for reactivation' },
        { num: '10-16%', label: 'Recovery target',    sub: 'From dormant opportunity pools' },
        { num: '12',     label: 'Website sections',   sub: 'Hero / VSL / Courses / FAQ' },
        { num: '5',      label: 'Lead capture forms', sub: 'All wired to WhatsApp' },
      ],
      built: [
        { icon: Globe,        color: 'signal' as const, title: 'React Sales Website', desc: 'Hero, VSL, courses, quiz, app showcase, FAQ, and clear CTA routing built with React/Vite/Tailwind.' },
        { icon: Smartphone,   color: 'violet' as const, title: 'AI Tracker App',      desc: 'Calorie and macro tracking direction with AI food recognition, client history, and coach-facing data.' },
        { icon: CheckCircle2, color: 'green'  as const, title: 'Lead Quiz Funnel',    desc: 'Interactive quiz that filters clients by program and fires a WhatsApp message automatically.' },
        { icon: Mail,         color: 'pink'   as const, title: 'Lead Reactivation',   desc: 'Follow-up sequence and segmentation plan to turn old lead records into booked conversations.' },
      ],
      before: [
        'WordPress site that never converted',
        '2,000 leads sitting untouched in a spreadsheet',
        'No social proof or testimonials',
        'No app for clients',
        'Everything done manually',
        '3-10 leads per month',
      ],
      after: [
        'Fast React site converting 24/7',
        'Reactivation system for 2,000+ records',
        'Social proof + measurable results',
        'AI-powered client tracking app',
        '5 forms auto-routing to WhatsApp',
        'Target: 80-100 qualified leads/month',
      ],
    },

    ron: {
      label: 'Case Study - E-Commerce',
      client: "Ron's Store",
      clientTitle: 'E-Commerce - 5,000+ Products',
      summary: "Ron needed a custom e-commerce platform that could handle a large catalog without turning every update into manual admin work. We built the structure for search, filtering, checkout, and back-office control.",
      deliverables: [
        'Custom React storefront with real-time search and advanced multi-filter system',
        'Full product catalog management for 5,000+ SKUs, variants, and inventory tracking',
        'Stripe Checkout + subscription support with webhook-powered order automation',
        'Admin dashboard: orders, inventory, analytics, and customer management',
        'Performance-optimized catalog structure built for thousands of products',
      ],
      metrics: [
        { num: '5,000+', label: 'Live products',    sub: 'Full catalog management' },
        { num: '<2s',    label: 'Page load time',   sub: 'Even with 5K SKUs' },
        { num: 'Hours',  label: 'Saved weekly',     sub: 'Bulk catalog/admin workflows' },
        { num: '24/7',   label: 'Auto fulfillment', sub: 'Webhook-powered orders' },
      ],
      built: [
        { icon: ShoppingCart, color: 'signal' as const, title: 'Custom Storefront',  desc: 'React storefront with real-time search, advanced filtering by category, price, and attributes.' },
        { icon: Package,      color: 'violet' as const, title: 'Catalog Engine',      desc: '5,000+ SKUs with variants, inventory, bulk import/export, and category management.' },
        { icon: CreditCard,   color: 'green'  as const, title: 'Stripe Checkout',    desc: 'Full payment flow with webhook automation: order confirmed, inventory updated, customer notified.' },
        { icon: Search,       color: 'pink'   as const, title: 'Admin Dashboard',    desc: 'Full back-office: orders, customers, analytics, and inventory management in one place.' },
      ],
      before: [
        'Shopify limitations blocking growth',
        'Slow load times with large catalog',
        'No custom filtering capabilities',
        'Manual order management',
        'No real analytics or insights',
        'Paying high monthly SaaS fees',
      ],
      after: [
        'Custom storefront with zero limitations',
        'Sub-2s load even with 5,000+ products',
        'Advanced multi-attribute filtering',
        'Fully automated order fulfillment',
        'Real-time analytics dashboard',
        'One-time build cost - own your platform',
      ],
    },
  },

  proofLedger: {
    label: 'Proof Ledger',
    headline: 'Concrete systems, not AI theater.',
    sub: 'Every item below ties the build to a business outcome: recovered demand, saved hours, clearer intake, faster handoff, or a cleaner path to revenue.',
    cards: [
      {
        icon: Mail,
        color: 'signal' as const,
        title: 'Dormant Lead Recovery',
        stat: '2,000+',
        statLabel: 'records audited',
        body: 'Mapped an old lead pool, split it by intent, and designed a 5-7 touch recovery path with WhatsApp handoff and owner-visible follow-up.',
        outcome: 'Target: recover 10-16% of dormant opportunities. At normal service-business ticket sizes, that is real cash from demand that already existed.',
      },
      {
        icon: Package,
        color: 'violet' as const,
        title: 'Large Catalog Systems',
        stat: '5,000+',
        statLabel: 'SKUs structured',
        body: 'Structured catalog, search, filtering, checkout, and admin workflows so a large product base is not managed one item at a time.',
        outcome: 'Cuts repeated catalog work, keeps checkout open 24/7, and gives the owner a platform they can actually operate.',
      },
      {
        icon: Globe,
        color: 'green' as const,
        title: 'Hebrew RTL Business Site',
        stat: 'RTL',
        statLabel: 'site + contact flow',
        body: 'Built a Hebrew-first local-business site with mobile layout, clear service/catalog paths, and contact flow for people who are ready to act.',
        outcome: 'Reduces confusion on the first visit and makes it easier for a real customer to understand, trust, and contact the business.',
      },
      {
        icon: FileText,
        color: 'pink' as const,
        title: 'Accounting Office Systems',
        stat: '4-9h',
        statLabel: 'weekly admin target',
        body: 'For accounting-office products, mapped systems for intake, recurring tasks, document tracking, approvals, reminders, and client handoff.',
        outcome: 'The win is simple: fewer missed tasks, less chasing, and more owner time recovered every week.',
      },
      {
        icon: Megaphone,
        color: 'signal' as const,
        title: 'Personal Brand Engine',
        stat: '1K+',
        statLabel: 'followers built',
        body: 'Built content systems around positioning, hooks, packaging, research, production rhythm, and feedback loops from real views and likes.',
        outcome: 'Turns posting into a measurable audience-building system instead of random content guesses.',
      },
      {
        icon: Workflow,
        color: 'violet' as const,
        title: 'Agency AI Agent Builds',
        stat: 'AI',
        statLabel: 'agent workflows',
        body: 'Scoped, specified, and built AI assistant workflows for business owners inside a larger AI-focused agency environment.',
        outcome: 'Moves teams from repeated manual questions and copy-paste work into documented, testable AI-assisted workflows.',
      },
      {
        icon: ShieldCheck,
        color: 'green' as const,
        title: 'Classified Military AI Systems',
        stat: 'Live',
        statLabel: 'classified work',
        body: 'Currently implementing modern AI systems inside classified military projects. The organization, branch, workflows, and operational details stay confidential.',
        outcome: 'Focus: reliable workflows, operational clarity, and practical AI adoption in a high-stakes environment where mistakes are expensive.',
      },
      {
        icon: Building2,
        color: 'pink' as const,
        title: 'Business App And Tooling',
        stat: 'Full',
        statLabel: 'web/app/system stack',
        body: 'Signal Lab is not limited to one tool. We build websites, apps, automations, bots, dashboards, internal tools, and the glue between them.',
        outcome: 'We choose the build by business logic: what removes the biggest pain and moves the owner toward the desired result fastest.',
      },
    ],
  },

  caseStudyLibrary: {
    label: 'Case Study Library',
    headline: 'Every proof item, separated.',
    sub: 'Each project has a different bottleneck, build, and business outcome. Sensitive military work is included only as a classified case study, never as a testimonial.',
    studies: [
      {
        icon: Globe,
        color: 'signal' as const,
        title: 'Tomer Friedman - Sales System',
        type: 'Sales website + funnel + reactivation',
        context: 'Fitness and nutrition operator with a real offer, old demand, and a site that did not turn attention into qualified next steps.',
        built: 'Rebuilt the sales website, quiz flow, WhatsApp routing, course structure, app direction, and reactivation path for 2,000+ dormant lead records.',
        outcome: 'The business moved from scattered manual follow-up into a clearer lead path with a 10-16% dormant-lead recovery target.',
        metrics: ['2,000+ lead records', '12 website sections', '5 WhatsApp lead forms'],
        tags: ['React', 'Vite', 'Lead Flow', 'WhatsApp'],
      },
      {
        icon: Smartphone,
        color: 'green' as const,
        title: 'TF Tracker - AI Nutrition App',
        type: 'Mobile app concept + build path',
        context: 'A coaching business needed a way to turn client tracking from screenshots and scattered updates into a usable mobile workflow.',
        built: 'Planned the iOS/Android tracker around food-photo recognition, client logging, nutrition history, coach-ready data, and subscription-ready app structure.',
        outcome: 'Creates a product path beyond service delivery: better client data, faster coaching review, and a foundation for recurring app value.',
        metrics: ['AI photo flow', 'Coach dashboard path', 'Mobile-first workflow'],
        tags: ['Expo', 'Supabase', 'Gemini AI', 'TypeScript'],
      },
      {
        icon: Globe,
        color: 'green' as const,
        title: 'Hahai VeHatzomeach - Hebrew RTL Site',
        type: 'Local business website',
        context: 'A Hebrew-first local business needed a mobile-first site that explains what they sell and makes contact/catalog browsing simple.',
        built: 'Built the RTL site structure, mobile layout, service clarity, catalog/contact paths, local-business positioning, and practical conversion flow.',
        outcome: 'Reduces first-visit confusion and gives customers a faster path from interest to understanding, trust, and contact.',
        metrics: ['RTL UX', 'Mobile-first', 'Catalog/contact path'],
        tags: ['React', 'RTL UX', 'Mobile', 'Lead Flow'],
      },
      {
        icon: FileText,
        color: 'pink' as const,
        title: 'Shova Ben Haim - Accounting Office Systems',
        type: 'Accounting workflow + product systems',
        context: 'Accounting offices lose hours in intake, recurring tasks, document status, approvals, reminders, and client handoff.',
        built: 'Mapped product/workflow systems for accounting firms: intake, document tracking, recurring office tasks, client handoff, dashboards, and AI-agent support paths.',
        outcome: 'Targets 4-9 hours of weekly admin reduction by making office status, responsibility, and next actions visible instead of buried in messages.',
        metrics: ['4-9h weekly admin target', 'Client handoff', 'Operational dashboards'],
        tags: ['Workflow Design', 'CRM', 'Dashboards', 'AI Agents'],
      },
      {
        icon: Workflow,
        color: 'violet' as const,
        title: 'Agency AI Agent Builds',
        type: 'AI assistant workflow layer',
        context: 'Business-owner operations inside a larger AI-focused agency needed AI workflows that are more than prompt experiments.',
        built: 'Scoped and built assistant workflows, source-of-truth structures, handoff logic, workflow maps, QA expectations, and repeatable operations for real business use cases.',
        outcome: 'Moves repeated questions, admin, and copy-paste work into documented AI-assisted workflows the team can test and improve.',
        metrics: ['AI workflow layer', 'QA + handoff', 'Business-owner use cases'],
        tags: ['OpenAI', 'n8n', 'Make', 'Workflow QA'],
      },
      {
        icon: Megaphone,
        color: 'signal' as const,
        title: 'Personal Brand Engine',
        type: 'Audience and content system',
        context: 'A content channel needed repeatable positioning, hooks, packaging, research, and feedback loops instead of random posting.',
        built: 'Built the content operating system: topic selection, hook testing, packaging, production rhythm, analytics review, and iteration from real views and likes.',
        outcome: 'Passed 1K+ followers while turning content into a measurable audience-building system instead of guesswork.',
        metrics: ['1K+ followers', 'Real views/likes', 'Feedback loop'],
        tags: ['Content Ops', 'Positioning', 'Analytics', 'AI Research'],
      },
      {
        icon: Package,
        color: 'violet' as const,
        title: 'Large Catalog System',
        type: 'E-commerce/catalog operations',
        context: 'Large product catalogs become painful when search, filtering, checkout, inventory, and admin updates are handled one item at a time.',
        built: 'Structured a 5,000+ SKU catalog/admin workflow with product organization, search, filtering, checkout structure, and repeatable back-office handling.',
        outcome: 'Cuts repeated catalog work and gives the owner an operating layer for a large product base instead of manual item-by-item chaos.',
        metrics: ['5,000+ SKUs', 'Search/filtering', 'Admin workflow'],
        tags: ['Catalog Ops', 'Search', 'Checkout', 'Admin'],
      },
      {
        icon: ShieldCheck,
        color: 'green' as const,
        title: 'Classified Military AI Systems',
        type: 'Ongoing classified AI systems work',
        context: 'Ongoing military projects in a classified environment. The organization, branch, workflows, data, and operational details are intentionally not public.',
        built: 'Implementing modern AI systems around reliable workflows, operational clarity, practical adoption, and safe handoff in a high-stakes environment.',
        outcome: 'The public takeaway is the standard of work: practical AI systems built where reliability, documentation, and confidentiality matter.',
        metrics: ['Ongoing', 'Classified', 'High-stakes workflows'],
        tags: ['AI Systems', 'Secure Workflows', 'Confidential', 'Operations'],
        confidential: true,
      },
    ],
  },

  testimonials: [
    {
      kind: 'testimonial' as const,
      name: 'Tomer Friedman',
      role: 'Nutritionist & Coach - tf-nutritionist.com',
      initials: 'TF',
      color: 'signal' as const,
      text: 'Yehonatan built my website, app, and marketing system from scratch. He understands both the business and the build, and he moved in weeks on work that usually gets dragged out for months.',
    },
    {
      kind: 'testimonial' as const,
      name: 'Ron',
      role: 'E-Commerce Founder',
      initials: 'R',
      color: 'violet' as const,
      text: 'Yehonatan is the kind of person you meet once in your career. Deep technical knowledge combined with real business thinking. He took our massive product catalog and built a platform that actually performs. The ROI was clear from day one.',
    },
    {
      kind: 'proof' as const,
      name: 'TF Tracker',
      role: 'AI nutrition app proof note',
      initials: 'AI',
      color: 'green' as const,
      text: 'The app work turns coaching data into a usable product path: food-photo recognition, client logging, coach review, and a cleaner route toward recurring app value.',
    },
    {
      kind: 'proof' as const,
      name: 'Hahai VeHatzomeach',
      role: 'Hebrew RTL local-business proof note',
      initials: 'HV',
      color: 'green' as const,
      text: 'The site was treated as a local-business conversion system: Hebrew-first structure, mobile clarity, catalog/contact paths, and less friction for customers who are ready to act.',
    },
    {
      kind: 'proof' as const,
      name: 'Shova Ben Haim Systems',
      role: 'Accounting workflow proof note',
      initials: 'SB',
      color: 'pink' as const,
      text: 'The work focuses on the places accounting offices actually leak time: intake, recurring tasks, document status, approvals, reminders, dashboards, and handoff.',
    },
    {
      kind: 'proof' as const,
      name: 'Agency AI Agent Builds',
      role: 'AI workflow proof note',
      initials: 'AI',
      color: 'violet' as const,
      text: 'The agent work is built around source-of-truth, workflow maps, QA, logs, and handoff, so AI becomes an operating layer instead of a demo prompt.',
    },
    {
      kind: 'proof' as const,
      name: 'Personal Brand Engine',
      role: 'Audience-system proof note',
      initials: '1K',
      color: 'signal' as const,
      text: 'The content system passed 1K+ followers through positioning, research, hooks, packaging, production rhythm, and feedback from real views and likes.',
    },
  ],

  process: [
    { num: '01', title: 'Free Audit',      desc: "We inspect your offer, workflow, leads, site, and follow-up path. The goal is to find the first leak worth fixing." },
    { num: '02', title: 'Money Map',       desc: 'We price the leak in hours, missed leads, or revenue, then define what should be built first and why.' },
    { num: '03', title: 'Build Sprint',    desc: 'Website, app, agent, automation, dashboard, or internal tool. You see the work while it is being built.' },
    { num: '04', title: 'Track Results',   desc: "Deploy, measure, optimize. We keep the work connected to saved time, recovered leads, or cleaner operations." },
  ],

  cta: {
    headline: 'Ready to build a system that gets you clients?',
    sub: 'Get a practical audit of the first leak we would fix, what it costs you, and what we would build to remove it.',
    primary: 'Get My Free AI Audit',
    secondary: 'Follow @signal.lab_',
  },

  leadMagnet: {
    // Popup + inline CTA
    badge: 'FREE - Limited Spots',
    headline: 'Get Your Free AI Growth Audit',
    subheadline: "Here's exactly what you get:",
    bullets: [
      'The first system we would build for your specific business',
      'The bottleneck costing you leads, hours, or revenue right now',
      'A prioritized roadmap: what to build first and why',
      'Honest assessment: what we would build if this were our business',
    ],
    why: "Most agencies pitch you a package before they understand your business. We do the homework first, so you get a real plan, not a sales deck.",
    ctaLabel: 'Send Me the Free Audit',
    namePlaceholder: 'Your name',
    emailPlaceholder: 'your@email.com',
    businessPlaceholder: 'Your website or business (optional)',
    disclaimer: 'Delivered to your inbox within 48h. Zero spam. Zero pitch.',
    successTitle: 'You are in.',
    successSub: 'Check your inbox in the next 48 hours. We will send you a personalized breakdown built specifically for your business.',
    // Popup triggers
    scrollTrigger: 55,   // % scroll depth
    exitIntent: true,
    delayTrigger: 45,    // seconds on page
  },
};
